const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=__dirname,A='000000000000000000000001',B='000000000000000000000002',F='000000000000000000000003',T='000000000000000000000004';
const rows=[];
const scope=(n,complete=true)=>({knownSubtotal:n,total:complete?n:null,isComplete:complete,missingComponents:complete?[]:[{reason:'travel_unpriced'}],valuationBases:[],workOrderCount:1,fullyPricedCount:complete?1:0});
const totals={lifetime:{total:10,count:1,scopes:{internal:scope(10,false),vendorDirect:scope(5),directMaintenance:scope(15,false)}},last12Months:{total:10,count:1,scopes:{internal:scope(10,false),vendorDirect:scope(5),directMaintenance:scope(15,false)}}};
let members=[A,B],assets=[{_id:A,purchase:{price:100000}},{_id:B}],handler,assetFilter,benchmarkFilter;
const response=()=>({status(n){this.code=n;return this;},json(data){this.body=data;return this;}});
const contract={_id:T,coveredAssets:members,vendorLinks:[]};
const ctx=vm.createContext({console,Date,Number,require,buildTenantFilter:()=>({facilityId:F}),mongoose:{Types:{ObjectId:{isValid:()=>true}}},Contract:{findOne:()=>({lean:async()=>contract})},resolveCurrentContractCoverage:c=>({assetIds:c.coveredAssets}),inspectVendorCoverage:()=>({}),});
let source=fs.readFileSync(root+'/contractLifecycle.txt','utf8').replace(/^import .*;\n/gm,'').replace('export async function','async function');vm.runInContext(source+'\nglobalThis.run=getContractLifecycleIntelligence;',ctx);
async function contractRun(missing=false){const r=response();await ctx.run({params:{id:T},headers:{},user:{role:'admin'},core:{post:async()=>({data:{assets:missing?assets.slice(0,1):assets}}),get:async()=>({data:{assessment:{schemaVersion:'asset-lifecycle-v2',replacementAssessment:{state:'insufficient_data'}},metrics:{currentBookValue:null,replacementRecommended:null,projectedAnnualMaintenance:10,maintenanceScopes:{last12Months:totals.last12Months.scopes}}}})}},r);return r.body;}
(async()=>{
let r=await contractRun();assert.equal(r.summary.estimatedReplacementValue,100000);assert.equal(r.summary.currentBookValue,0);assert.equal(r.summary.replacementRecommendedCount,0);assert.equal(r.summary.replacementRecommendedPercent,0);rows.push({name:'partial_capital_and_insufficient_review',summary:r.summary});
r=await contractRun(true);assert.equal(r.summary.coveredAssetCount,2);assert.equal(r.summary.hydratedAssetCount,1);assert.equal(r.summary.estimatedReplacementValue,100000);rows.push({name:'missing_hydration',summary:r.summary});
contract.coveredAssets=[];assets=[];r=await contractRun();assert.equal(r.summary.replacementRecommendedPercent,0);rows.push({name:'empty_contract',summary:r.summary});
let data=[{_id:A,status:'Active',facilityId:F},{_id:B,status:'Inactive',facilityId:F},{_id:'P',status:'Pending',facilityId:F},{_id:'R',status:'Retired',facilityId:F},{_id:'X',status:'Active',facilityId:F,isArchived:true},{_id:'D',status:'Active',facilityId:F,deletedAt:'2020-01-01'},{_id:'FOREIGN',status:'Active',facilityId:'foreign'}];
function match(asset,q){return (!q.facilityId||String(q.facilityId)===asset.facilityId)&&(!q.status||asset.status!=='Retired')&&(!q.isArchived||!asset.isArchived)&&(!Object.hasOwn(q,'deletedAt')||!asset.deletedAt);}
const query=(q,kind)=>({select(){return this;},lean:async()=>{if(kind==='summary')assetFilter=q;else benchmarkFilter=q;return data.filter(a=>match(a,q));}});
const tmplCtx=vm.createContext({console,Date,Number,Object,Map,Set,buildTenantFilter:()=>({facilityId:F}),mongoose:{Types:{ObjectId:Object.assign(function(v){this.toString=()=>v;},{isValid:()=>true})}},Asset:{find:q=>query(q,'summary')},EquipmentTemplate:{findById:()=>({lean:async()=>({_id:T})})},authenticateToken:()=>{},authorizeRoles:()=>()=>{},router:{get:(_p,...handlers)=>{handler=handlers.at(-1);}},getTemplateMaintenanceBenchmarks:async()=>({tenant:{},global:{}}),require:path=>path.includes('lifecycleMaintenance')?{default:{getMaintenanceTotalsBatch:async ids=>new Map(ids.map(id=>[String(id),totals]))}}:require('../../src/utils/lifecycle')});
source=fs.readFileSync(root+'/templateLifecycle.txt','utf8');vm.runInContext(source,tmplCtx);let tr=response();await handler({params:{id:T},headers:{'x-facility-id':F},user:{role:'admin'}},tr);assert.equal(tr.body.summary.totalAssets,4);assert.equal(tr.body.summary.ageBuckets['0-2'],4);rows.push({name:'template_cohort_and_unknown_age',summary:tr.body.summary,predicate:assetFilter});
const benchCtx=vm.createContext({console,Date,Number,Object,Map,Set,Asset:{find:q=>query(q,'benchmark')},getMaintenanceTotalsBatch:async ids=>new Map(ids.map(id=>[String(id),totals]))});source=fs.readFileSync(root+'/templateLifecycleBenchmarks.txt','utf8').replace(/^import .*;\n/gm,'').replace('export async function','async function');vm.runInContext(source+'\nglobalThis.run=getTemplateMaintenanceBenchmarks;',benchCtx);const b=await benchCtx.run(T,{facilityId:F});assert.equal(b.tenant.sampleAssets,4);assert.equal(b.global.sampleAssets,5);assert.equal(b.tenant.avgAnnualMaintenance,10);assert.equal(b.tenant.scopes.directMaintenance.knownSubtotal,60);assert.equal(b.tenant.scopes.directMaintenance.completeAssetCount,0);rows.push({name:'benchmark_cohort_and_narrow_scope',benchmark:b,predicate:benchmarkFilter});
data=[];tr=response();await handler({params:{id:T},headers:{'x-facility-id':F},user:{role:'admin'}},tr);assert.equal(tr.body.summary.replacementRecommendedPercent,0);rows.push({name:'empty_template',summary:tr.body.summary});
console.log(JSON.stringify({baseline:'cf862e5218172ba274799b4287d20dea38198f74',rows},null,2));
})();
