#version: "3.8"

networks:
  cronus-network:
    driver: bridge

volumes:
  mongo-data:

services:
  # --------------------------
  # LOCAL MONGO PROFILE
  # --------------------------
  mongo:
    profiles: ["localmongo"]
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - cronus-network

  core-service:
    profiles: ["localmongo"]
    build: ./core-service
    command: npm run dev
    ports:
      - "4000:4000"
    environment:
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      PORT: 4000
      TZ: "America/New_York"
    volumes:
      - ./core-service:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - cronus-network

  contract-service:
    profiles: ["localmongo"]
    build: ./contract-service
    command: npm run dev
    ports:
      - "5001:5001"
    environment:
      MONGO_URI: ${MONGO_URI}
      CORE_API_URL: "http://core-service:4000"
      JWT_SECRET: ${JWT_SECRET}
      PORT: 5001
      CRON_ENABLED: ${CRON_ENABLED:-true}
      TZ: "America/New_York"
    volumes:
      - ./contract-service:/app
      - /app/node_modules
    depends_on:
      - mongo
      - core-service
    networks:
      - cronus-network

  frontend:
    profiles: ["localmongo"]
    build: ./frontend
    command: npm run dev
    ports:
      - "5173:5173"
    environment:
      VITE_CORE_API_URL: "http://192.168.1.185:4000"
      VITE_CONTRACT_API_URL: "http://192.168.1.185:5001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - core-service
      - contract-service
    networks:
      - cronus-network


  # --------------------------
  # ATLAS PROFILE
  # --------------------------
  core-service-atlas:
    profiles: ["atlas"]
    build: ./core-service
    command: npm run dev
    ports:
      - "4000:4000"
    environment:
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      PORT: 4000
      TZ: "America/New_York"
    volumes:
      - ./core-service:/app
      - /app/node_modules
    networks:
      - cronus-network

  contract-service-atlas:
    profiles: ["atlas"]
    build: ./contract-service
    command: npm run dev
    ports:
      - "5001:5001"
    environment:
      MONGO_URI: ${MONGO_URI}
      CORE_API_URL: "http://core-service-atlas:4000"
      JWT_SECRET: ${JWT_SECRET}
      PORT: 5001
      CRON_ENABLED: ${CRON_ENABLED:-true}
      TZ: "America/New_York"
    volumes:
      - ./contract-service:/app
      - /app/node_modules
    depends_on:
      - core-service-atlas
    networks:
      - cronus-network

  frontend-atlas:
    profiles: ["atlas"]
    build: ./frontend
    command: npm run dev
    ports:
      - "5173:5173"
    environment:
      VITE_CORE_API_URL: "http://localhost:4000"
      VITE_CONTRACT_API_URL: "http://localhost:5001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - core-service-atlas
      - contract-service-atlas
    networks:
      - cronus-network

