const fs=require('fs'),vm=require('vm'),assert=require('assert');const dir=__dirname;
const asset={_id:'A',ctrlNumber:'Synthetic',status:'Active',metrics:{replacementRecommended:true,projectedAnnualMaintenance:999,yearsInService:0,computedAt:'2000-01-01'},templateId:{benchmark:{expectedUsefulLifeYears:5,averageQuotedPrice:100000}},lifecycleCache:{schemaVersion:'obsolete',policyVersion:'obsolete',validUntil:'2000-01-01'}};
const {buildAssetLifecycleAssessment}=require('../../src/services/assetLifecycleAssessment');
const economics=require('../../src/services/workOrderCosts/calculate');const scopes=Object.fromEntries(['internal','vendorDirect','directMaintenance'].map(name=>[name,economics.summarize([],name)]));const totals={lifetime:{count:0,total:0,scopes},last12Months:{count:0,total:0,scopes}};
const live=buildAssetLifecycleAssessment({asset:{...asset,serviceStartDate:'2026-01-01',lifecyclePolicy:{sourceType:'asset_override',expectedLifeYears:50,reference:'synthetic-approved',approvedBy:'000000000000000000000003',approvedAt:'2025-01-01'}},template:asset.templateId,maintenanceTotals:totals,asOf:new Date('2026-10-07')});assert.equal(live.replacementAssessment.state,'not_recommended');
const queryChain=rows=>({sort(){return this},select(){return this},populate(){return this},skip(){return this},limit(){return this},lean:async()=>rows});let handler,query;
class FrozenDate extends Date{constructor(...args){super(...(args.length?args:['2026-10-07T00:00:00Z']));}static now(){return Date.parse('2026-10-07T00:00:00Z');}}
const globals={console:{log(){},error(){}},Date:FrozenDate,Math,Number,Object,authenticateToken(){},buildTenantFilter:()=>({}),mongoose:{Types:{ObjectId:{isValid:()=>true}}},Asset:{find:q=>{query=q;return queryChain([asset]);},countDocuments:async()=>1},assetRouter:{get:(_p,...h)=>handler=h.at(-1)},dashboardRouter:{get:(_p,...h)=>handler=h.at(-1)}};
const response=()=>({status(){return this},json(body){this.body=body;}});
(async()=>{let res=response();vm.runInNewContext(fs.readFileSync(dir+'/assetList.txt','utf8'),globals);await handler({query:{replacementRecommended:'true',highMaintenance:'true'}},res);assert.equal(res.body.assets.length,1);assert.equal(query['metrics.replacementRecommended'],true);assert.equal(query['metrics.projectedAnnualMaintenance'].$gt,0);assert.equal(res.body.lifecycleFilterCoverage,undefined);
const rows=[{name:'stale_recommendation_and_maintenance_filter',query,stored:asset.metrics,canonical:{replacementAssessment:live.replacementAssessment,directMaintenance:live.maintenance.last365Days.directMaintenance},matches:1},{name:'version_policy_and_time_drift_ignored',cache:asset.lifecycleCache,matches:1}];
res=response();vm.runInNewContext(fs.readFileSync(dir+'/forecast.txt','utf8'),globals);await handler({},res);assert.equal(res.body.totalForecastedAssets,1);assert.equal(res.body.totalEstimatedCapitalNeed,100000);rows.push({name:'stale_forecast_unknown_age_interpretation',forecast:res.body});
asset.templateId.benchmark.expectedUsefulLifeYears=50;asset.templateId.benchmark.averageQuotedPrice=200000;asset.metrics.projectedAnnualMaintenance=999;res=response();vm.runInNewContext(fs.readFileSync(dir+'/assetList.txt','utf8'),globals);await handler({query:{replacementRecommended:'true',highMaintenance:'true'}},res);assert.equal(res.body.assets.length,1);rows.push({name:'template_and_workorder_change_no_invalidation',matches:1,storedMaintenance:999,canonicalMaintenanceAfterEconomicEdit:10});
const module={exports:{}};let scheduled;vm.runInNewContext(fs.readFileSync(dir+'/scheduler.txt','utf8'),{console:{log(){}},module,require:name=>name==='node-cron'?{schedule:(_p,fn)=>scheduled=fn}:name.includes('Asset')?{find:()=>queryChain([{_id:'A',templateId:'T'}])}:{}});let error;try{await scheduled();}catch(e){error=e.message;}assert.match(error,/mongoose is not defined/);rows.push({name:'scheduler_missing_import',error});let moduleError;try{new vm.Script(fs.readFileSync(dir+'/maintenanceModule.txt','utf8'));}catch(e){moduleError=e.message;}assert.match(moduleError,/Cannot use import statement outside a module/);rows.push({name:'native_commonjs_maintenance_dependency',error:moduleError});console.log(JSON.stringify({baseline:'6ecb58714c8eab7b1797f72ed94a29df8854cb5c',rows},null,2));})();
