// src/services/index.ts
export * from "./apiClient"
export * from "./assetAPI"
export * from "./workOrderAPI"
export * from "./departmentAPI"
export * from "./templateAPI"
export * from "./contractClient"
export * from "./contractAPI"
export * from "./procedureAPI"
//export * from "./procedureAPI"
