import {render,screen,within} from '@testing-library/react';
import {expect,test} from 'vitest';
import Card from './AssetLifecycleCard';
import type {Asset,AssetLifecycleResponse} from '@/types';
import type {AssetLifecycleAssessment,ReplacementReviewState} from '@/types/AssetLifecycleAssessment';
const asset:Asset={_id:'synthetic',ctrlNumber:'SYN-20',manufacturer:'Synthetic',model:'Pump',facilityId:'synthetic',metrics:{yearsInService:0,replacementRecommended:false,currentBookValue:999}};
function assessment():AssetLifecycleAssessment{return {
 schemaVersion:'asset-lifecycle-v2',assetId:asset._id,asOf:'2026-01-01T00:00:00Z',computedAt:'2026-01-01T00:00:00Z',versions:{lifecycleCalculation:'v2',lifecyclePolicy:'synthetic',economicCalculation:'wo-cost-v1'},
 serviceAge:{startDate:null,years:null,status:'unknown',source:null,isProxy:false},expectedLife:{years:null,status:'unknown',isAdopted:false,source:null},
 capital:{acquisitionBasis:{amount:null,currency:null,status:'unknown'},estimatedDepreciatedValue:{amount:null,currency:null,status:'insufficient_data',missingInputs:['acquisition_basis']},accountingBookValue:{amount:null,currency:null,status:'not_available'},replacementValue:{amount:100000,currency:null,status:'estimated',source:{type:'template_average_quoted_price'}},salvage:{rawAmount:0,recordedAmount:null,planningAmount:0,basis:'assumption',reference:'synthetic'}},
 maintenance:{primaryScope:'directMaintenance',window:{start:'2025-01-01T00:00:00Z',end:'2026-01-01T00:00:00Z',startInclusive:true,endInclusive:true,dateField:'completionDate',statuses:['Completed']},lifetime:null,last365Days:{directMaintenance:{knownSubtotal:1200,total:null,isComplete:false,missingComponents:[{component:'internalTravel',reason:'unpriced'}]}}},
 replacementAssessment:{state:'insufficient_data',meaning:'replacement_review',reasonCodes:['service_age_unknown'],displayText:'Service start is unknown.',rules:[]},quality:{missingFields:['acquisition_basis'],assumptions:['zero_planning_salvage'],conflicts:[]},
};}
function response(a=assessment()):AssetLifecycleResponse{return {assetId:asset._id,purchase:null,metrics:{},assessment:a};}
const show=(a=assessment())=>render(<Card asset={asset} lifecycle={response(a)} />);
test('unknown is not zero or green Within Expected Life',()=>{show();expect(within(screen.getByRole('region',{name:'Service age'})).getByText('Unknown')).toBeVisible();expect(screen.queryByText('0.00 years')).toBeNull();expect(screen.queryByText('Within Expected Life')).toBeNull();expect(screen.getByRole('status')).toHaveTextContent('Insufficient data');expect(screen.queryByRole('progressbar')).toBeNull();});
for(const [state,text] of [['not_started','Not started'],['invalid','Invalid service date']] as const)test(`${state} shown explicitly`,()=>{const a=assessment();a.serviceAge.status=state;show(a);expect(screen.getByText(text)).toBeVisible();expect(screen.queryByText('0.00 years')).toBeNull();});
test('estimated service age exposes proxy',()=>{const a=assessment();a.serviceAge={years:2,startDate:'2024-01-01',status:'estimated',source:{type:'acquisition_proxy'},isProxy:true};show(a);expect(screen.getByText('2.00 years (estimated proxy)')).toBeVisible();expect(screen.getByText('Estimated from acquisition date')).toBeVisible();});
test('true zero age is displayed',()=>{const a=assessment();a.serviceAge={years:0,startDate:a.asOf,status:'resolved',source:{type:'service_start'},isProxy:false};show(a);expect(screen.getByText('0.00 years')).toBeVisible();});
test('canonical policy life wins unrelated raw benchmark',()=>{const a=assessment();a.expectedLife={years:5,status:'resolved',isAdopted:true,source:{type:'asset_override'}};render(<Card asset={{...asset,templateId:{_id:'template',benchmark:{expectedUsefulLifeYears:99}}}} lifecycle={response(a)} />);expect(screen.getByText('5 years')).toBeVisible();expect(screen.getByText('Approved Asset policy')).toBeVisible();expect(screen.queryByText('99 years')).toBeNull();});
test('unadopted benchmark labeled reference',()=>{const a=assessment();a.expectedLife={years:null,referenceYears:7,status:'reference_only',isAdopted:false,source:{type:'external_reference'}};show(a);expect(screen.getByText('Reference: 7 years; not adopted as policy.')).toBeVisible();});
test('capital meanings separated without fabricated USD',()=>{show();const capital=screen.getByRole('region',{name:'Lifecycle capital'});expect(within(capital).getByText('Acquisition Basis')).toBeVisible();expect(within(capital).getByText('Estimated Depreciated Value')).toBeVisible();expect(within(capital).getByText('Accounting Book Value')).toBeVisible();expect(within(capital).getByText('Replacement Estimate')).toBeVisible();expect(within(capital).getByText('100,000 (currency unspecified)')).toBeVisible();expect(screen.queryByText('$100,000.00')).toBeNull();expect(screen.queryByText('Current Book Value')).toBeNull();});
test('declared currency formatted',()=>{const a=assessment();a.capital.acquisitionBasis={amount:50,currency:'USD',status:'recorded'};show(a);expect(screen.getByText('$50.00')).toBeVisible();});
test('planning zero salvage clearly assumed',()=>{show();expect(screen.getByText(/Planning salvage: 0 — zero salvage assumption/)).toBeVisible();expect(screen.getByText(/recorded salvage is not known zero/)).toBeVisible();});
test('incomplete direct maintenance shows subtotal and missing component',()=>{show();const costs=screen.getByRole('region',{name:'Direct maintenance costs'});expect(within(costs).getByText('Direct Maintenance Cost — Last 365 Days')).toBeVisible();expect(within(costs).getByText('Incomplete — known subtotal $1,200.00')).toBeVisible();expect(within(costs).getByText('Missing components: internalTravel')).toBeVisible();expect(screen.queryByText('Projected Annual Maintenance')).toBeNull();});
test('complete direct maintenance displays total',()=>{const a=assessment();a.maintenance.last365Days={directMaintenance:{knownSubtotal:20,total:20,isComplete:true,missingComponents:[]}};show(a);expect(screen.getByText('$20.00')).toBeVisible();expect(screen.queryByText(/Incomplete — known subtotal/)).toBeNull();});
for(const [state,text] of [['recommended','Recommended for replacement review'],['not_recommended','Replacement review not recommended'],['insufficient_data','Insufficient data for replacement review']] satisfies [ReplacementReviewState,string][])test(`${state} review badge`,()=>{const a=assessment();a.replacementAssessment.state=state;show(a);expect(screen.getByRole('status')).toHaveTextContent(text);expect(screen.getByText(/not a mandatory replacement instruction/)).toBeVisible();});
test('legacy response/cache does not fabricate canonical assessment',()=>{render(<Card asset={asset} lifecycle={{assetId:asset._id,purchase:null,metrics:asset.metrics!}} />);expect(screen.getByRole('status')).toHaveTextContent('assessment unavailable');expect(screen.queryByText('Within Expected Life')).toBeNull();expect(screen.queryByText('$999.00')).toBeNull();});
test('loading and failure are explicit',()=>{const v=render(<Card asset={asset} isLoading />);expect(screen.getByText(/Loading lifecycle assessment/)).toBeVisible();v.rerender(<Card asset={asset} error={new Error('synthetic')} />);expect(screen.getByRole('alert')).toHaveTextContent('Unable to load');});
